### ISSUE TITLE
Plan for 4.1.0

### ISSUE THREAD

**Issue by st0012** [getsentry/sentry-ruby#1146]
- [x] Merge the tracing and exception capturing middleware into one https://github.com/getsentry/sentry-ruby/pull/1147
  - Requires document change
- [x] Deep-copy spans to avoid concurrency issue when using manually https://github.com/getsentry/sentry-ruby/pull/1148
- [x] Make Rack integration optional https://github.com/getsentry/sentry-ruby/issues/1136
- [x] Add queue worker https://github.com/getsentry/sentry-ruby/issues/1130
- [x] Make the Rake integration Rails 6.1 compatible https://github.com/getsentry/sentry-ruby/issues/1145
- other bug fixes
