### ISSUE TITLE
[ruby] Add metrics

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-ruby#2246]
https://github.com/getsentry/team-sdks/issues/36
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-ruby/pull/2247
- [ ] https://github.com/getsentry/sentry-ruby/pull/2254
- [ ] https://github.com/getsentry/sentry-ruby/pull/2255
- [ ] https://github.com/getsentry/sentry-ruby/pull/2258
- [ ] https://github.com/getsentry/sentry-ruby/pull/2263
```
